// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb8SYBjVYs8vWiLyQxfrjAXZUT2W7PbGM',
    appId: '1:981095620510:web:c3ffda8bf831e251a7c08f',
    messagingSenderId: '981095620510',
    projectId: 'app-do-verdemar-2a0a8',
    authDomain: 'app-do-verdemar-2a0a8.firebaseapp.com',
    storageBucket: 'app-do-verdemar-2a0a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0f9RBPzQM0L6qkOMa_q3V60398C3xnTA',
    appId: '1:981095620510:android:b5510c583f147262a7c08f',
    messagingSenderId: '981095620510',
    projectId: 'app-do-verdemar-2a0a8',
    storageBucket: 'app-do-verdemar-2a0a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhMsIc4Spy5zNWH3_tf7vVEL_ionYGMM',
    appId: '1:981095620510:ios:11ecc2e61821879ba7c08f',
    messagingSenderId: '981095620510',
    projectId: 'app-do-verdemar-2a0a8',
    storageBucket: 'app-do-verdemar-2a0a8.firebasestorage.app',
    iosBundleId: 'com.example.controlePontosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjhMsIc4Spy5zNWH3_tf7vVEL_ionYGMM',
    appId: '1:981095620510:ios:11ecc2e61821879ba7c08f',
    messagingSenderId: '981095620510',
    projectId: 'app-do-verdemar-2a0a8',
    storageBucket: 'app-do-verdemar-2a0a8.firebasestorage.app',
    iosBundleId: 'com.example.controlePontosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb8SYBjVYs8vWiLyQxfrjAXZUT2W7PbGM',
    appId: '1:981095620510:web:d2f765d62086a1dca7c08f',
    messagingSenderId: '981095620510',
    projectId: 'app-do-verdemar-2a0a8',
    authDomain: 'app-do-verdemar-2a0a8.firebaseapp.com',
    storageBucket: 'app-do-verdemar-2a0a8.firebasestorage.app',
  );
}
